### PR TITLE
Fixes #522 CRD and operator conform to fluentd-loki-output-plugin documentation

### LINKED ISSUE #522: bug: fluentd loki output plugin integration not conform to the plugin configuration
### Describe the issue

The fluentd loki output plugin integration generate a fluentd configuration that doesn't fit the plugin configuration expectations.  
CRDs and operator wait for `host` and `port` parameters while plugin waits for `url`

### To Reproduce

Create a `ClusterOutput` as follow:

```yaml
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: cluster-fluentd-output-loki
  labels:
    output.fluentd.fluent.io/scope: "antrema"
    output.fluentd.fluent.io/enabled: "true"
spec: 
  outputs: 
  - loki:
      host: "loki.loki.svc"
      port: 3100
```
This `ClusterOutput` is conform to the CRDs: `host` and `port` parameters are defined.
The generated configuration is as follow:

```
<source>
  @type  forward
  bind  0.0.0.0
  port  24224
</source>
<match **>
  @id  main
  @type  label_router
  <route>
    @label  @4a7489aeb8a1024f96f1cf69234e2764
    <match>
      namespaces  default,fluent,kube-system,loki
    </match>
  </route>
</match>
<label @4a7489aeb8a1024f96f1cf69234e2764>
  <match **>
    @id  ClusterFluentdConfig-cluster-cluster-fluentd-config::cluster::clusteroutput::cluster-fluentd-output-loki-0
    @type  loki
    host  loki.loki.svc
    port  3100
  </match>
</label>
```
While the fluentd-loki-output-plugin [documentation](https://grafana.com/docs/loki/latest/clients/fluentd/#usage) refers to
```
<match **>
  @type loki
  url "https://logs-prod-us-central1.grafana.net"
  username "#{ENV['LOKI_USERNAME']}"
  password "#{ENV['LOKI_PASSWORD']}"
  extra_labels {"env":"dev"}
  flush_interval 10s
  flush_at_shutdown true
  buffer_chunk_limit 1m
</match>
```

### Expected behavior

The CRD and operator should be conform to the plugin documentation, so should accept `url` parameter instead of `host` and `port`
The `ClusterOutput` definition will become:
```yaml
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: cluster-fluentd-output-loki
  labels:
    output.fluentd.fluent.io/scope: "antrema"
    output.fluentd.fluent.io/enabled: "true"
spec: 
  outputs: 
  - loki:
      url: "http://loki.loki.svc:3100"
```

### Your Environment

```markdown
- Fluent Operator version: kubesphere/fluent-operator:v1.7.0; docker.io/kubesphere/fluent-operator@sha256:be402a3040b4eaec43157c4ac5126c038876eedd5d095db1a78da4ccbce6ced1
- Container Runtime: containerd://1.6.6-k3s1 
- Operating system: Linux/AMD64
- Kernel version: 5.4.0-135-generic
```

### How did you install fluent operator?

I installed the fluent-operator as described in fluent-operator [documentation](https://github.com/fluent/fluent-operator#deploy-fluent-operator-with-yaml)

```bash
kubectl create ns fluent 
kubectl apply -f https://raw.githubusercontent.com/fluent/fluent-operator/release-1.7/manifests/setup/setup.yaml
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by antrema**
### Which issue(s) this PR fixes:
Fixes #522 Made CRD and operator conform to fluentd-loki-output-plugin documentation

### Does this PR introduced a user-facing change?
```release-note
None
```

### Additional documentation, usage docs, etc.:
```docs

```

### CODE REVIEW

File: apis/fluentd/v1alpha1/plugins/tls_types.go [hunk 1]
```diff
@@ -6,24 +6,14 @@ import (
 
 // Fluentd provides integrated support for Transport Layer Security (TLS) and it predecessor Secure Sockets Layer (SSL) respectively.
 type TLS struct {
-	// Force certificate validation
-	Verify *bool `json:"verify,omitempty"`
-	// Set TLS debug verbosity level.
-	// It accept the following values: 0 (No debug), 1 (Error), 2 (State change), 3 (Informational) and 4 Verbose
-	// +kubebuilder:validation:Enum:=0;1;2;3;4
-	Debug *int32 `json:"debug,omitempty"`
```
Comment (wenchajun) [inline apis/fluentd/v1alpha1/plugins/tls_types.go:14]: This is a public document, is it necessary to remove these sections?

File: apis/fluentd/v1alpha1/plugins/tls_types.go [hunk 2]
```diff
@@ -6,24 +6,14 @@ import (
 
 // Fluentd provides integrated support for Transport Layer Security (TLS) and it predecessor Secure Sockets Layer (SSL) respectively.
 type TLS struct {
-	// Force certificate validation
-	Verify *bool `json:"verify,omitempty"`
```
Comment (benjaminhuo) [inline apis/fluentd/v1alpha1/plugins/tls_types.go:10]: why removing fields in TLS?

File: apis/fluentd/v1alpha1/plugins/tls_types.go (hunk 1 above)
Comment (antrema) [reply apis/fluentd/v1alpha1/plugins/tls_types.go:14]: It is not necessary, but it is not interpreted in the controller

File: apis/fluentd/v1alpha1/plugins/tls_types.go (hunk 2 above)
Comment (antrema) [reply apis/fluentd/v1alpha1/plugins/tls_types.go:10]: there are not used in controller

File: apis/fluentd/v1alpha1/plugins/tls_types.go (hunk 1 above)
Comment (antrema) [reply apis/fluentd/v1alpha1/plugins/tls_types.go:14]: Ok, I understand your point of view, but if I undelete them, they will be automatically added to the CRD, you don't think it can be confusing ? what do you think about unlinking the loki struct from the *plugins.TLS struct ?

**Comment by benjaminhuo** [comment]
It's true that the Fluentd Loki plugin is copy from fluentbit Loki plugin which is incorrect.
The `TLS` is from fluentbit https://docs.fluentbit.io/manual/pipeline/outputs/tcp-and-tls https://docs.fluentbit.io/manual/pipeline/outputs/opensearch

@wenchajun @wanjunlei Please double check if the `TLS` should be removed from the fluentd code

File: apis/fluentd/v1alpha1/plugins/tls_types.go (hunk 1 above)
Comment (wenchajun) [reply apis/fluentd/v1alpha1/plugins/tls_types.go:14]: https://docs.fluentd.org/configuration/transport-section
For the data structure of `tls` one should refer to the official documentation, so I don't think these should be removed, and as for any missing parts we will add them later.

**Comment by wanjunlei** [comment]
> It's true that the Fluentd Loki plugin is copy from fluentbit Loki plugin which is incorrect. The `TLS` is from fluentbit https://docs.fluentbit.io/manual/pipeline/outputs/tcp-and-tls https://docs.fluentbit.io/manual/pipeline/outputs/opensearch
> 
> @wenchajun @wanjunlei Please double check if the `TLS` should be removed from the fluentd code

The fluentd plugin `http`,  `forward` have their own tls settings and does not use the `TLS`, so I think loki can set its own tls
settings like them.

And the fluentd plugins do not have a common tls setting, so I agree to delete the `TLS`, and the plugins should define the tls setting themselves

**Comment by benjaminhuo** [comment]
> The fluentd plugin `http`, `forward` have their own tls settings and does not use the `TLS`, so I think loki can set its own tls settings like them.
> 
> And the fluentd plugins do not have a common tls setting, so I agree to delete the `TLS`, and the plugins should define the tls setting themselves

Agree, @antrema would you please make these changes accordingly?

File: apis/fluentd/v1alpha1/plugins/tls_types.go (hunk 1 above)
Comment (benjaminhuo) [reply apis/fluentd/v1alpha1/plugins/tls_types.go:14]: The tls docs for fluentd https://github.com/fluent/fluent-operator/blob/master/docs/plugins/fluentd/tls.md is copied from [fluentbit tls setting](https://docs.fluentbit.io/manual/pipeline/outputs/tcp-and-tls) which is incorrect.

As @wenchajun mentioned fluentd has its own [tls setting](https://docs.fluentd.org/configuration/transport-section) which is different with fluentbit's and should be optional to the fluentd input and output plugins: `The transport section must be under <match>, <source>, and <filter> sections. It specifies the transport protocol, version, and certificates.`

So fluentd's tls setting should conformed to fluentd's doc, not fluentbit's: https://docs.fluentd.org/configuration/transport-section 

Fluentd's tls setting should include params from 5 sections:
- https://docs.fluentd.org/configuration/transport-section#tls-setting
- https://docs.fluentd.org/configuration/transport-section#signed-public-ca-parameters
- https://docs.fluentd.org/configuration/transport-section#generated-and-signed-by-private-ca-parameters
- https://docs.fluentd.org/configuration/transport-section#generated-and-signed-by-private-ca-certs-or-self-signed-parameters
- https://docs.fluentd.org/configuration/transport-section#cert-digest-algorithm-parameter

Fluentd tls samples:
https://stackoverflow.com/questions/50190993/how-to-get-fluentd-td-agent-tls-ssl-encryption-for-in-forward-to-work
https://github.com/fluent/fluentd/issues/3802

**Review by benjaminhuo — CHANGES_REQUESTED** [review]

**Comment by benjaminhuo** [comment]
> > It's true that the Fluentd Loki plugin is copy from fluentbit Loki plugin which is incorrect. The `TLS` is from fluentbit https://docs.fluentbit.io/manual/pipeline/outputs/tcp-and-tls https://docs.fluentbit.io/manual/pipeline/outputs/opensearch
> > @wenchajun @wanjunlei Please double check if the `TLS` should be removed from the fluentd code
> 
> The fluentd plugin `http`, `forward` have their own tls settings and does not use the `TLS`, so I think loki can set its own tls settings like them.
> 
> And the fluentd plugins do not have a common tls setting, so I agree to delete the `TLS`, and the plugins should define the tls setting themselves

See my comments in https://github.com/fluent/fluent-operator/pull/523#discussion_r1089666748

**Comment by wanjunlei** [comment]
There has been a [Transport](https://github.com/fluent/fluent-operator/blob/master/apis/fluentd/v1alpha1/plugins/common/common_types.go#L77) struct.

**Comment by benjaminhuo** [comment]
> There has been a [Transport](https://github.com/fluent/fluent-operator/blob/master/apis/fluentd/v1alpha1/plugins/common/common_types.go#L77) struct.

Nice, then we should use [Transport](https://github.com/fluent/fluent-operator/blob/master/apis/fluentd/v1alpha1/plugins/common/common_types.go#L77)  instead of the `TLS` in Loki @antrema

**Comment by antrema** [comment]
> > There has been a [Transport](https://github.com/fluent/fluent-operator/blob/master/apis/fluentd/v1alpha1/plugins/common/common_types.go#L77) struct.
> 
> Nice, then we should use [Transport](https://github.com/fluent/fluent-operator/blob/master/apis/fluentd/v1alpha1/plugins/common/common_types.go#L77) instead of the `TLS` in Loki @antrema

You completely lost me
The plugin `fluentd-loki-output-plugin` is maintained by Grafana and its definition is fully documented [here](https://grafana.com/docs/loki/latest/clients/fluentd/#fluentd-loki-output-plugin)
Why do you want to absolutely match an existing struct (`Transport` or `TLS`), the resulting CRDs will completely differ from the plugin `fluentd-loki-output-plugin` documentation and users will be confused
I think we just have to match the `Loki` struct to the plugin structure
As it is done on the other output plugins:
  * like `Forward`output plugin: https://github.com/fluent/fluent-operator/blob/master/apis/fluentd/v1alpha1/plugins/output/forward.go
  * like `Http` output plugin: https://github.com/fluent/fluent-operator/blob/master/apis/fluentd/v1alpha1/plugins/output/http.go
In both `struct` the TLS parameters are completely redefined to match 

To make me clear, i will rework my PR to match my explanations

**Comment by benjaminhuo** [comment]
> The plugin `fluentd-loki-output-plugin` is maintained by Grafana and its definition is fully documented [here](https://grafana.com/docs/loki/latest/clients/fluentd/#fluentd-loki-output-plugin)
> Why do you want to absolutely match an existing struct (`Transport` or `TLS`), the resulting CRDs will completely differ from the plugin `fluentd-loki-output-plugin` documentation and users will be confused
> I think we just have to match the `Loki` struct to the plugin structure

@antrema You're right. It should be consistent with the plugin def.
The [HTTP input plugin](https://docs.fluentd.org/input/http) has the transport section in which the tls config should be put.
But the [HTTP output plugin](https://docs.fluentd.org/output/http) simply put tls settings as plain fields.

Thanks for finding and fixing this bug!

**Review by benjaminhuo — APPROVED** [review]
